/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig_1.h"
#include "AMux_1.h"
#include "X_Input.h"
#include "X_Input_aliases.h"
#include "Y_Input.h"
#include "Y_Input_aliases.h"
#include "LCD_Char_1.h"
#include "USBFS_1.h"
#include "USBFS_1_audio.h"
#include "USBFS_1_cdc.h"
#include "USBFS_1_hid.h"
#include "USBFS_1_midi.h"
#include "USBFS_1_pvt.h"
#include "Button_A.h"
#include "Button_A_aliases.h"
#include "Button_B.h"
#include "Button_B_aliases.h"
#include "Button_C.h"
#include "Button_C_aliases.h"
#include "Button_D.h"
#include "Button_D_aliases.h"
#include "Thumb_Button.h"
#include "Thumb_Button_aliases.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "LCD_Char_1_LCDPort.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "USBFS_1_Dm.h"
#include "USBFS_1_Dm_aliases.h"
#include "USBFS_1_Dp.h"
#include "USBFS_1_Dp_aliases.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"

/*[]*/

